version: '2'
services:
    veare:
        restart: always
        #image: veare/veare:latest
        build:
            context: .
            args:
                npm: "true"
        container_name: veare
        volumes:
            - ../../veare:/usr/src/app
        networks:
            - docker_appnet
        command: sh start.sh
        ports:
            - "8080:8080"
# used for interal communication within docker
networks:
    docker_appnet:
        external: true
